[features]
seeds = false

# [programs.localnet]
# solkitties = "C7KGdk3H9yTvZF7TDPeJJwvNo5jMSie4onZ3XLzToTVc"

[programs.devnet]
solkitties = "C7KGdk3H9yTvZF7TDPeJJwvNo5jMSie4onZ3XLzToTVc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/earth/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init-state = "ts-node client/index.ts"